### ISSUE TITLE
is there a way to map to <control ;> like keynav?

### ISSUE THREAD

**Issue by ghost** [h2ero/XEasyMotion#9]
i put .xeasymotionrc to ~/ but the app does not seems to read the config file

Thanks for making the app though

**Comment by makerneo-com** [comment]
: ( this function is not implemented.

**Comment by CRThaze** [comment]
Here's a tip on how to do that with Automator:
1. Create a 'Service' Workflow
2. Add 'Launch Application' and select 'XEasyMotion.app'
3. Save
4. In System Preferences, under Keyboard -> Shortcuts -> Services, find your workflow service and map any key combination you like to it.

**Comment by heywoodlh** [comment]
I know this issue is super old but I ran into it and thought I'd document it in case anyone wanted to use [skhd](https://github.com/koekeishiya/skhd) for this. 

I placed the downloaded app in `~/Applications/keynav.app` so with that assumption, here's the relevant `skhd` snippet:

```
ctrl - 0x29 : bash -c "~/Applications/keynav.app/Contents/MacOS/XEasyMotion"
```

That allows me to launch the app with `ctrl + ;` like keynav.
